### ISSUE TITLE
Validation failed: User must existエラー対処

### ISSUE THREAD

**Issue by shu0115** [shu0115/funbox#86]
```
funbox   · New error    ActiveRecord::RecordInvalid ·sessions#callback  Validation failed: User must exist Oct 23rd 10:33:13  utc  P \|     app/models/authentication.rb:61 · create_with_omniauth app/controllers/sessions_controller.rb:7 · callback    Release stage production   Severity error   Request URL https://funbox.herokuapp.com/auth/twitter/callback?oauth_token=h1WjvQAAAAAAV_dYAAABX0jLFB8&oauth_verifier=W8BFnkKiQJlerJT1hq3fxetlH9JoZk14    view on bugsnag  Directly reply to this email to collaborate on this error.  View available email commands    © Bugsnag 2016 · 939 Harrison St., San Francisco, CA, 94107 · We're hiring!  Manage email notifications | funbox   · New error    ActiveRecord::RecordInvalid ·sessions#callback  Validation failed: User must exist Oct 23rd 10:33:13  utc  P \|     app/models/authentication.rb:61 · create_with_omniauth app/controllers/sessions_controller.rb:7 · callback    Release stage production   Severity error   Request URL https://funbox.herokuapp.com/auth/twitter/callback?oauth_token=h1WjvQAAAAAAV_dYAAABX0jLFB8&oauth_verifier=W8BFnkKiQJlerJT1hq3fxetlH9JoZk14    view on bugsnag  Directly reply to this email to collaborate on this error.  View available email commands    © Bugsnag 2016 · 939 Harrison St., San Francisco, CA, 94107 · We're hiring!  Manage email notifications | funbox | · | New error | ActiveRecord::RecordInvalid ·sessions#callback  Validation failed: User must exist Oct 23rd 10:33:13  utc | P \| | P | \| |   | app/models/authentication.rb:61 · create_with_omniauth | app/controllers/sessions_controller.rb:7 · callback | Release stage | production | Severity | error | Request URL | https://funbox.herokuapp.com/auth/twitter/callback?oauth_token=h1WjvQAAAAAAV_dYAAABX0jLFB8&oauth_verifier=W8BFnkKiQJlerJT1hq3fxetlH9JoZk14
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
funbox   · New error    ActiveRecord::RecordInvalid ·sessions#callback  Validation failed: User must exist Oct 23rd 10:33:13  utc  P \|     app/models/authentication.rb:61 · create_with_omniauth app/controllers/sessions_controller.rb:7 · callback    Release stage production   Severity error   Request URL https://funbox.herokuapp.com/auth/twitter/callback?oauth_token=h1WjvQAAAAAAV_dYAAABX0jLFB8&oauth_verifier=W8BFnkKiQJlerJT1hq3fxetlH9JoZk14    view on bugsnag  Directly reply to this email to collaborate on this error.  View available email commands    © Bugsnag 2016 · 939 Harrison St., San Francisco, CA, 94107 · We're hiring!  Manage email notifications | funbox | · | New error | ActiveRecord::RecordInvalid ·sessions#callback  Validation failed: User must exist Oct 23rd 10:33:13  utc | P \| | P | \| |   | app/models/authentication.rb:61 · create_with_omniauth | app/controllers/sessions_controller.rb:7 · callback | Release stage | production | Severity | error | Request URL | https://funbox.herokuapp.com/auth/twitter/callback?oauth_token=h1WjvQAAAAAAV_dYAAABX0jLFB8&oauth_verifier=W8BFnkKiQJlerJT1hq3fxetlH9JoZk14
funbox | · | New error
ActiveRecord::RecordInvalid ·sessions#callback  Validation failed: User must exist Oct 23rd 10:33:13  utc | P \| | P | \| |  
P | \| |  
app/models/authentication.rb:61 · create_with_omniauth
app/controllers/sessions_controller.rb:7 · callback
Release stage | production
Severity | error
Request URL | https://funbox.herokuapp.com/auth/twitter/callback?oauth_token=h1WjvQAAAAAAV_dYAAABX0jLFB8&oauth_verifier=W8BFnkKiQJlerJT1hq3fxetlH9JoZk14


```

```
ActiveRecord::RecordInvalid   Occured in SessionsController#callback on funbox (production)      MESSAGE Validation failed: User must exist     PATH /auth/twitter/callback     IN FILE vendor/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'     ON HOST e2947bfe-f1d5-4f0f-8135-68787e8417ce      View in AppSignal          Don't care for these emails? Change your notification settings.  We will send you other emails about this exception if it occurs after a cooldown of 5 minutes.  Have any questions? support@appsignal.com |   | ActiveRecord::RecordInvalid   Occured in SessionsController#callback on funbox (production) | MESSAGE Validation failed: User must exist | PATH /auth/twitter/callback | IN FILE vendor/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize' | ON HOST e2947bfe-f1d5-4f0f-8135-68787e8417ce | View in AppSignal | Don't care for these emails? Change your notification settings.  We will send you other emails about this exception if it occurs after a cooldown of 5 minutes.  Have any questions? support@appsignal.com
-- | -- | -- | -- | -- | -- | -- | -- | --
 
ActiveRecord::RecordInvalid   Occured in SessionsController#callback on funbox (production)
MESSAGE Validation failed: User must exist
PATH /auth/twitter/callback
IN FILE vendor/ruby-2.4.1/lib/ruby/2.4.0/monitor.rb:214:in `mon_synchronize'
ON HOST e2947bfe-f1d5-4f0f-8135-68787e8417ce
View in AppSignal
Don't care for these emails? Change your notification settings.  We will send you other emails about this exception if it occurs after a cooldown of 5 minutes.  Have any questions? support@appsignal.com


```

**Comment by shu0115** [comment]
DONE
